# Generated by Django 4.1.3 on 2023-12-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userid_username_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
