# Generated by Django 4.1.3 on 2023-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rdes', models.TextField()),
                ('rphot', models.ImageField(upload_to='recipy_img')),
            ],
        ),
    ]
